local utils = require("polar.utils")
local config = require("polar.config").options.styles.bufferline

local bufferline = {}

local c = require("polar.colors").palette

function bufferline.highlights()
  local current_hi = vim.tbl_extend("force", { bg = c.polar_night.brighter }, config.current)
  local global_bg = utils.make_global_bg(true)

  return {
    -- Barbar
    BufferTabpageFill = { bg = global_bg, fg = c.polar_night.origin },
    BufferCurrent = current_hi,
    BufferCurrentIndex = current_hi,
    BufferCurrentMod = vim.tbl_extend("force", { bg = c.polar_night.brighter, fg = c.aurora.yellow }, config.modified),
    BufferCurrentSign = vim.tbl_extend("force", current_hi, { fg = c.frost.arctic_water }),
    BufferCurrentTarget = vim.tbl_extend(
      "force",
      { bg = c.polar_night.brighter, fg = c.aurora.red, bold = true },
      config.current
    ),
    BufferCurrentHINT = vim.tbl_extend("force", current_hi, { fg = c.frost.arctic_water }),
    BufferCurrentINFO = vim.tbl_extend("force", current_hi, { fg = c.frost.ice }),
    BufferCurrentWARN = vim.tbl_extend("force", current_hi, { fg = c.aurora.yellow }),
    BufferCurrentERROR = vim.tbl_extend("force", current_hi, { fg = c.aurora.red }),
    BufferVisible = { bg = c.polar_night.bright },
    BufferVisibleIndex = { bg = c.polar_night.bright },
    BufferVisibleMod = vim.tbl_extend("force", { bg = c.polar_night.bright, fg = c.aurora.yellow }, config.modified),
    BufferVisibleSign = { bg = c.polar_night.bright, fg = c.frost.arctic_water },
    BufferVisibleTarget = { bg = c.polar_night.bright, fg = c.aurora.red, bold = true },
    BufferVisibleHINT = { bg = c.polar_night.bright, fg = c.frost.arctic_water },
    BufferVisibleINFO = { bg = c.polar_night.bright, fg = c.frost.ice },
    BufferVisibleWARN = { bg = c.polar_night.bright, fg = c.aurora.yellow },
    BufferVisibleERROR = { bg = c.polar_night.bright, fg = c.aurora.red },
    BufferInactive = { bg = global_bg, fg = c.polar_night.light },
    BufferInactiveIndex = { bg = global_bg, fg = c.polar_night.light },
    BufferInactiveMod = vim.tbl_extend(
      "force",
      { bg = global_bg, fg = utils.darken(c.aurora.yellow, 0.4) },
      config.modified
    ),
    BufferInactiveSign = { bg = global_bg, fg = c.polar_night.origin },
    BufferInactiveTarget = { bg = global_bg, fg = c.aurora.red, bold = true },
    BufferInactiveHINT = { bg = global_bg, fg = utils.darken(c.frost.arctic_water, 0.4) },
    BufferInactiveINFO = { bg = global_bg, fg = utils.darken(c.frost.ice, 0.4) },
    BufferInactiveWARN = { bg = global_bg, fg = utils.darken(c.aurora.yellow, 0.4) },
    BufferInactiveERROR = { bg = global_bg, fg = utils.darken(c.aurora.red, 0.4) },
    BufferTabpages = { bg = global_bg, fg = c.none },
    BufferTabpage = { bg = global_bg, fg = c.none },
    BufferLineBackground = { fg = c.none, bg = c.none },
    BufferLineBuffer = { fg = c.none, bg = c.none },
    BufferLineBufferSelected = { bg = c.none, fg = c.snow_storm.origin },
    BufferLineBufferVisible = { bg = c.none },
    BufferLineCloseButton = { bg = c.none },
    BufferLineCloseButtonSelected = { bg = c.none },
    BufferLineCloseButtonVisible = { bg = c.none },
    BufferLineDuplicate = { bg = c.none },
    BufferLineDuplicateSelected = { bg = c.none },
    BufferLineDuplicateVisible = { bg = c.none },
    BufferLineError = { bg = c.none, sp = c.none },
    BufferLineErrorDiagnostic = { bg = c.none, sp = c.none },
    BufferLineErrorDiagnosticSelected = { bg = c.none, sp = c.none },
    BufferLineErrorDiagnosticVisible = { bg = c.none },
    BufferLineErrorSelected = { bg = c.none, sp = c.none },
    BufferLineErrorVisible = { bg = c.none },
    BufferLineFill = { bg = c.none },
    BufferLineHint = { sp = c.none, bg = c.none },
    BufferLineHintDiagnostic = { sp = c.none, bg = c.none },
    BufferLineHintDiagnosticSelected = { bg = c.none, sp = c.none },
    BufferLineHintDiagnosticVisible = { bg = c.none },
    BufferLineHintSelected = { bg = c.none, sp = c.none },
    BufferLineHintVisible = { bg = c.none },
    BufferLineInfo = { sp = c.none, bg = c.none },
    BufferLineInfoDiagnostic = { sp = c.none, bg = c.none },
    BufferLineInfoDiagnosticSelected = { sp = c.none, bg = c.none },
    BufferLineInfoDiagnosticVisible = { bg = c.none },
    BufferLineInfoSelected = { bg = c.none, sp = c.none },
    BufferLineInfoVisible = { bg = c.none },
    BufferLineIndicatorSelected = { bg = c.none },
    BufferLineModified = { bg = c.none },
    BufferLineModifiedSelected = { bg = c.none },
    BufferLineModifiedVisible = { bg = c.none },
    BufferLineNumbers = { bg = c.none },
    BufferLineNumbersSelected = { bg = c.none },
    BufferLineNumbersVisible = { bg = c.none },
    BufferLineOffsetSeparator = { bg = c.none },
    BufferLineSeparator = { bg = c.none },
    BufferLineSeparatorSelected = { bg = c.none },
    BufferLineSeparatorVisible = { bg = c.none },
    BufferLineTab = { bg = c.none },
    BufferLinePick = { bg = c.none },
    BufferLinePickSelected = { bg = c.none },
    BufferLineDevIconLua = { bg = c.none },
    BufferLineDevIconLuaSelected = { bg = c.none },
    BufferLineDevIconLuaVisible = { bg = c.none },
    BufferLineDevIconLuaInactive = { bg = c.none },
    BufferLinePickVisible = { bg = c.none },
    BufferLineIndicatorVisible = { bg = c.none },
    BufferLineTabClose = { bg = c.none },
    BufferLineTabSelected = { bg = c.none },
    BufferLineTabSeparator = { bg = c.none },
    BufferLineTabSeparatorSelected = { bg = c.none },
    BufferLineTruncMarker = { bg = c.none },
    BufferLineWarning = { bg = c.none },
    BufferLineWarningDiagnostic = { bg = c.none },
    BufferLineWarningDiagnosticSelected = { bg = c.none },
    BufferLineWarningDiagnosticVisible = { bg = c.none },
    BufferLineWarningSelected = { bg = c.none },
    BufferLineWarningVisible = { bg = c.none },
  }
end

function bufferline.akinsho()
  local current_hi =
    vim.tbl_extend("force", { bg = c.polar_night.brighter, italic = false, bold = false }, config.current)
  local global_bg = utils.make_global_bg(true)

  return {
    fill = { bg = global_bg, fg = c.polar_night.light },
    background = { bg = global_bg, fg = c.polar_night.light },
    numbers = { bg = global_bg },
    close_button = { bg = global_bg },
    separator = { bg = global_bg, fg = c.polar_night.origin },
    duplicate = { bg = global_bg },
    modified = vim.tbl_extend("force", { bg = global_bg, fg = utils.darken(c.aurora.yellow, 0.4) }, config.modified),
    pick = { bg = global_bg, bold = true, italic = false },
    diagnostic = { bg = global_bg },
    hint = { bg = global_bg, fg = utils.darken(c.frost.arctic_water, 0.6) },
    hint_diagnostic = { bg = global_bg, fg = utils.darken(c.frost.arctic_water, 0.6) },
    info = { bg = global_bg, fg = utils.darken(c.frost.ice, 0.6) },
    info_diagnostic = { bg = global_bg, fg = utils.darken(c.frost.ice, 0.6) },
    warning = { bg = global_bg, fg = utils.darken(c.aurora.yellow, 0.6) },
    warning_diagnostic = { bg = global_bg, fg = utils.darken(c.aurora.yellow, 0.6) },
    error_diagnostic = { bg = global_bg, fg = utils.darken(c.aurora.red, 0.6) },
    error = { bg = global_bg, fg = utils.darken(c.aurora.red, 0.6) },
    buffer_selected = current_hi,
    numbers_selected = current_hi,
    close_button_selected = current_hi,
    modified_selected = vim.tbl_extend("force", { bg = c.polar_night.brighter, fg = c.aurora.yellow }, config.modified),
    separator_selected = { bg = c.polar_night.brighter, fg = c.polar_night.origin },
    duplicate_selected = current_hi,
    pick_selected = vim.tbl_extend("force", current_hi, { bold = true }),
    indicator_selected = { fg = c.frost.arctic_water, bg = c.polar_night.brighter },
    indicator_visible = { fg = c.frost.arctic_ocean, bg = c.polar_night.bright },
    diagnostic_selected = current_hi,
    hint_selected = vim.tbl_extend("force", current_hi, { fg = c.frost.arctic_water }),
    hint_diagnostic_selected = vim.tbl_extend("force", current_hi, { fg = c.frost.arctic_water }),
    info_selected = vim.tbl_extend("force", current_hi, { fg = c.frost.ice }),
    info_diagnostic_selected = vim.tbl_extend("force", current_hi, { fg = c.frost.ice }),
    warning_selected = vim.tbl_extend("force", current_hi, { fg = c.aurora.yellow }),
    warning_diagnostic_selected = vim.tbl_extend("force", current_hi, { fg = c.aurora.yellow }),
    error_selected = vim.tbl_extend("force", current_hi, { fg = c.aurora.red }),
    error_diagnostic_selected = vim.tbl_extend("force", current_hi, { fg = c.aurora.red }),
    buffer_visible = { bg = c.polar_night.bright },
    numbers_visible = { bg = c.polar_night.bright },
    close_button_visible = { bg = c.polar_night.bright },
    modified_visible = vim.tbl_extend("force", { bg = c.polar_night.bright, fg = c.aurora.yellow }, config.modified),
    separator_visible = { bg = global_bg, fg = c.polar_night.origin },
    duplicate_visible = { bg = c.polar_night.bright },
    pick_visible = { bg = c.polar_night.bright, bold = true, italic = false },
    diagnostic_visible = { bg = c.polar_night.bright },
    hint_visible = { bg = c.polar_night.bright, fg = c.frost.arctic_water },
    hint_diagnostic_visible = { bg = c.polar_night.bright, fg = c.frost.arctic_water },
    info_visible = { bg = c.polar_night.bright, fg = c.frost.ice },
    info_diagnostic_visible = { bg = c.polar_night.bright, fg = c.frost.ice },
    warning_visible = { bg = c.polar_night.bright, fg = c.aurora.yellow },
    warning_diagnostic_visible = { bg = c.polar_night.bright, fg = c.aurora.yellow },
    error_visible = { bg = c.polar_night.bright, fg = c.aurora.red },
    error_diagnostic_visible = { bg = c.polar_night.bright, fg = c.aurora.red },
    tab = { fg = c.snow_storm.origin, bg = global_bg },
    tab_selected = { fg = c.snow_storm.origin, bg = c.polar_night.brighter },
    tab_separator = { fg = c.polar_night.origin, bg = global_bg },
    tab_separator_selected = { fg = c.aurora.purple, bg = c.polar_night.brighter },
    tab_close = { fg = c.snow_storm.origin, bg = global_bg },
    trunc_marker = { bg = global_bg, fg = c.polar_night.light },
  }
end

return bufferline
